// ─── Work Allocation Page (WorkforcePage) ─────────────────────────────────────
// This page gives GAMA Consulting project managers a centralised view of
// workforce assignment across all active projects — replacing the manual
// Excel spreadsheet tracking they used before this system.
//
// The page has three views:
//   1. ProjectsList   — grid of clickable project cards
//   2. ProjectDetail  — drill-down view with tasks, materials, and workforce
//   3. AllocationModal — popup for adding/removing team members from a project
//
// Navigation between list and detail is handled with local state (master-detail
// pattern) rather than router navigation, keeping URLs simple.
// ─────────────────────────────────────────────────────────────────────────────

import { assignWorker } from "@/api/workforce"
import { createFileRoute } from "@tanstack/react-router"
import { useEffect, useState } from "react"
import { getWorkforce } from "@/client/workforce"
import { toast } from "sonner"

// Register this file as the /workforce route with TanStack Router.
// File location in src/routes/ determines the URL path automatically.
export const Route = createFileRoute("/workforce")({
  component: WorkforcePage,
})

// ─── TYPE DEFINITIONS ─────────────────────────────────────────────────────────
// TypeScript interfaces define the shape of data used throughout this file.
// This prevents runtime errors by catching type mismatches at compile time.

// Base worker — represents any employee in the system
interface Worker {
  id: number
  name: string
  role: string
  status?: "active" | "completed" | "available" // optional — not all contexts need status
}

// ProjectWorker extends Worker with an assignedRole specific to this project.
// The same employee can have different roles on different projects.
interface ProjectWorker extends Worker {
  assignedRole: string
}

// Full project object — contains all data shown in the detail view
interface Project {
  id: string
  code: string
  name: string
  department: string
  location: string
  startDate: string
  deliveryDate: string
  progress: number // 0–100 overall completion percentage
  status: "Completed" | "In Progress" | "Planning"
  aiInsight: { message: string; detail: string; confidence: number }
  tasks: { name: string; progress: number }[]
  materials: { name: string; qty: string; status: "Delivered" | "Pending" | "In Transit" }[]
  workforce: ProjectWorker[]
}

// ─── MOCK DATA ────────────────────────────────────────────────────────────────
// Hardcoded project data used while the real backend projects API is being
// integrated. In production, this will be replaced with a fetch from
// GET /api/v1/projects which returns the same Project shape.
const MOCK_PROJECTS: Project[] = [
  {
    id: "PRJ-2024-003",
    code: "PRJ-2024-003",
    name: "Bridge Renovation Project",
    department: "City Infrastructure Department",
    location: "River District",
    startDate: "Nov 1, 2023",
    deliveryDate: "Mar 15, 2024",
    progress: 100,
    status: "Completed",
    // AI insight is generated by the backend based on milestone completion and risk scoring
    aiInsight: {
      message: "Project Successfully Completed",
      detail: "All phases completed on time and within budget. Excellent team performance throughout the project lifecycle.",
      confidence: 100,
    },
    tasks: [
      { name: "Planning",    progress: 100 },
      { name: "Foundation",  progress: 100 },
      { name: "Structural",  progress: 100 },
      { name: "MEP",         progress: 100 },
      { name: "Finishing",   progress: 100 },
    ],
    materials: [
      { name: "Steel Beams",          qty: "180 tons", status: "Delivered" },
      { name: "Concrete Mix",         qty: "900 m³",   status: "Delivered" },
      { name: "Reinforcement Bars",   qty: "75 tons",  status: "Delivered" },
    ],
    workforce: [
      { id: 1, name: "Harri Rassias",  role: "Structural Engineer", assignedRole: "Structural Engineer", status: "completed" },
      { id: 2, name: "Robert Johnson", role: "Project Manager",      assignedRole: "Project Manager",      status: "completed" },
    ],
  },
  {
    id: "PRJ-2024-004",
    code: "PRJ-2024-004",
    name: "City Park Redevelopment",
    department: "Parks & Recreation",
    location: "Northside",
    startDate: "Jan 15, 2024",
    deliveryDate: "Jun 30, 2024",
    progress: 62,
    status: "In Progress",
    aiInsight: {
      message: "On Track — Minor Risk",
      detail: "Material deliveries running 3 days behind schedule. Recommend pre-ordering Phase 3 supplies now.",
      confidence: 87,
    },
    tasks: [
      { name: "Site Clearing", progress: 100 },
      { name: "Landscaping",   progress: 80 },
      { name: "Pathways",      progress: 55 },
      { name: "Amenities",     progress: 30 },
      { name: "Lighting",      progress: 0 },
    ],
    materials: [
      { name: "Paving Stones",       qty: "2,400 m²", status: "Delivered"  },
      { name: "Topsoil",             qty: "340 m³",   status: "In Transit" },
      { name: "Playground Equipment",qty: "1 set",    status: "Pending"    },
    ],
    workforce: [
      { id: 3, name: "Sarah Chen", role: "Landscape Architect", assignedRole: "Lead Designer", status: "active" },
    ],
  },
]

// ─── NAVIGATION ITEMS ─────────────────────────────────────────────────────────
// Sidebar navigation labels. "Projects" is the active page.
// Other items show "coming soon" until their routes are implemented.
const NAV_ITEMS = [
  { label: "Dashboard" },
  { label: "Projects", active: true },
  { label: "Task Board" },
  { label: "Subcontractors" },
  { label: "AI Assistant" },
  { label: "Settings" },
]

// ─── COLOUR HELPERS ───────────────────────────────────────────────────────────

// Maps project status strings to their badge background and text colours.
// Using a lookup object is cleaner than repeated if/else chains and
// makes it easy to add new statuses in one place.
const STATUS_COLOURS: Record<string, { bg: string; text: string }> = {
  Completed:     { bg: "#dcfce7", text: "#16a34a" }, // green
  "In Progress": { bg: "#dbeafe", text: "#2563eb" }, // blue
  Planning:      { bg: "#fef9c3", text: "#ca8a04" }, // amber
}

// Returns a colour based on progress percentage — used for progress bars
// and the circular SVG ring in the project header.
// Green = complete, Blue = on track, Amber = slowing, Red = critical
function progressColor(pct: number) {
  if (pct === 100) return "#22c55e" // green  — complete
  if (pct >= 60)   return "#3b82f6" // blue   — healthy progress
  if (pct >= 30)   return "#f59e0b" // amber  — falling behind
  return "#ef4444"                  // red    — critical
}

// Fixed palette of 8 colours used for worker avatar circles
const AVATAR_PALETTE = [
  "#3b82f6", "#8b5cf6", "#ec4899", "#f97316",
  "#14b8a6", "#6366f1", "#22c55e", "#f43f5e",
]

// Deterministically maps a name string to a colour from AVATAR_PALETTE.
// Uses a polynomial rolling hash (multiplier 31) so the same name always
// produces the same colour without storing preferences anywhere.
// The bitwise AND with 0xffffffff keeps the number within 32-bit range.
function avatarColor(name: string) {
  let h = 0
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) & 0xffffffff
  return AVATAR_PALETTE[Math.abs(h) % AVATAR_PALETTE.length]
}

// ─── CIRCULAR PROGRESS COMPONENT ─────────────────────────────────────────────
// Renders a circular SVG progress ring showing overall project completion.
// Built with raw SVG to avoid adding a charting library dependency.
//
// How it works:
//   - Two <circle> elements are drawn at the same position
//   - The background circle is grey and always full
//   - The progress circle uses strokeDasharray to show only (pct/100) of its circumference
//   - Circumference = 2 * π * radius = 2 * 3.14159 * 42 ≈ 264px
//   - dash = percentage of that circumference to colour in
//   - The SVG is rotated -90deg so progress starts from the top (12 o'clock)
function CircleProgress({ pct }: { pct: number }) {
  const r    = 42                    // radius in pixels
  const circ = 2 * Math.PI * r      // full circumference (~264px)
  const dash = (pct / 100) * circ   // how many pixels of arc to fill
  const color = progressColor(pct)

  return (
    <div style={{ position: "relative", width: 96, height: 96 }}>
      {/* SVG rotated so 0% starts at the top rather than the right */}
      <svg width="96" height="96" style={{ transform: "rotate(-90deg)" }}>
        {/* Background ring — always full grey circle */}
        <circle cx="48" cy="48" r={r} fill="none" stroke="#e5e7eb" strokeWidth="7" />
        {/* Progress arc — length controlled by strokeDasharray */}
        <circle
          cx="48" cy="48" r={r} fill="none"
          stroke={color} strokeWidth="7"
          strokeDasharray={`${dash} ${circ}`} // dash = filled, circ-dash = gap
          strokeLinecap="round"
        />
      </svg>
      {/* Percentage label centred over the ring using absolute positioning */}
      <div style={{
        position: "absolute", inset: 0,
        display: "flex", flexDirection: "column",
        alignItems: "center", justifyContent: "center",
      }}>
        <span style={{ fontSize: 16, fontWeight: 700, color }}>{pct}%</span>
        <span style={{ fontSize: 9, color: "#9ca3af", letterSpacing: "0.04em" }}>Overall Progress</span>
      </div>
    </div>
  )
}

// ─── WORKFORCE ALLOCATION MODAL ───────────────────────────────────────────────
// Popup dialog for adding and removing team members from a project.
//
// Props:
//   workers — the current workforce array for the project
//   onClose — called when the user clicks Cancel or closes the modal
//   onSave  — called with the updated workforce array when Save is clicked
//
// The modal manages its own local copy of the workforce (rows state) so
// changes are only committed to the parent when Save is clicked.
// Clicking Cancel discards all changes made in the modal session.
function AllocationModal({
  workers,
  onClose,
  onSave,
}: {
  workers: ProjectWorker[]
  onClose: () => void
  onSave: (updated: ProjectWorker[]) => void
}) {
  // Local copy of the workforce — edits here don't affect the parent until Save
  const [rows, setRows] = useState<ProjectWorker[]>(workers)

  // Controlled state for the two dropdown selectors
  const [employee, setEmployee] = useState("")
  const [role, setRole]         = useState("")

  // Available role options — in production these would come from GET /api/v1/roles
  const ROLE_OPTIONS = [
    "Project Manager", "Structural Engineer", "Frontend Developer",
    "Backend Developer", "Security Engineer", "Site Supervisor",
    "Landscape Architect", "MEP Engineer",
  ]

  // Available employee options — in production these would come from GET /api/v1/users
  const EMPLOYEE_OPTIONS = [
    "Alice Martin", "Bob Chen", "Charlie Davis", "Diana Ross",
    "Harri Rassias", "Robert Johnson", "Sarah Chen", "Marcus Lee",
  ]

  // Adds a new worker to the local rows array.
  // Guard clause returns early if either dropdown is empty.
  // Date.now() generates a unique numeric ID from the current timestamp —
  // guaranteed unique within a session since time always moves forward.
  // In production, the backend would assign a real UUID on save.
  const handleAdd = () => {
    if (!employee || !role) return // both fields required
    const newRow: ProjectWorker = {
      id: Date.now(), // temporary client-side ID
      name: employee,
      role,
      assignedRole: role,
      status: "active",
    }
    // Spread operator copies all existing rows then appends the new one
    setRows((prev) => [...prev, newRow])
    // Reset dropdowns so the user can add another worker immediately
    setEmployee("")
    setRole("")
  }

  // Removes a worker by filtering out the one with the matching ID.
  // filter() returns a new array excluding the removed worker —
  // React state requires a new array reference to trigger a re-render.
  const handleRemove = (id: number) => setRows((prev) => prev.filter((r) => r.id !== id))

  return (
    // Full-screen semi-transparent overlay — clicking outside doesn't close
    // (intentional — prevents accidental data loss)
    <div style={{
      position: "fixed", inset: 0, zIndex: 50,
      background: "rgba(0,0,0,0.35)",
      display: "flex", alignItems: "center", justifyContent: "center",
    }}>
      {/* Modal card — fixed width, scrollable body */}
      <div style={{
        background: "#fff",
        borderRadius: 12,
        boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
        width: 480,
        maxHeight: "80vh", // prevents modal exceeding viewport on small screens
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
      }}>

        {/* ── Modal Header ── */}
        <div style={{ padding: "24px 28px 16px" }}>
          <div style={{ fontSize: 18, fontWeight: 700, color: "#111827" }}>
            Workforce Allocation
          </div>
          <div style={{ fontSize: 13, color: "#6b7280", marginTop: 2 }}>
            Increase your team power
          </div>
        </div>

        {/* ── Add Row — Employee + Role dropdowns + Add button ── */}
        <div style={{ display: "flex", gap: 10, padding: "0 28px 16px", alignItems: "center" }}>

          {/* Employee dropdown — controlled by employee state */}
          <select
            value={employee}
            onChange={(e) => setEmployee(e.target.value)}
            style={{
              flex: 1, padding: "9px 12px",
              border: "1px solid #d1d5db", borderRadius: 8,
              fontSize: 13, color: "#374151", background: "#fff",
              outline: "none", cursor: "pointer",
            }}
          >
            <option value="">Employee</option>
            {EMPLOYEE_OPTIONS.map((e) => <option key={e}>{e}</option>)}
          </select>

          {/* Role dropdown — controlled by role state */}
          <select
            value={role}
            onChange={(e) => setRole(e.target.value)}
            style={{
              flex: 1, padding: "9px 12px",
              border: "1px solid #d1d5db", borderRadius: 8,
              fontSize: 13, color: "#374151", background: "#fff",
              outline: "none", cursor: "pointer",
            }}
          >
            <option value="">Role</option>
            {ROLE_OPTIONS.map((r) => <option key={r}>{r}</option>)}
          </select>

          {/* Add button — calls handleAdd which validates both fields first */}
          <button
            onClick={handleAdd}
            style={{
              padding: "9px 20px", background: "#2563eb", color: "#fff",
              border: "none", borderRadius: 8, fontSize: 13,
              fontWeight: 600, cursor: "pointer",
            }}
          >
            Add
          </button>
        </div>

        {/* ── Workers Table ── */}
        {/* Scrollable section — flex: 1 makes it fill remaining modal height */}
        <div style={{ borderTop: "1px solid #f3f4f6", overflowY: "auto", flex: 1 }}>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ background: "#f9fafb" }}>
                <th style={{ padding: "10px 28px", textAlign: "left", fontSize: 12, fontWeight: 600, color: "#6b7280", letterSpacing: "0.03em" }}>
                  Employee Name
                </th>
                <th style={{ padding: "10px 16px", textAlign: "left", fontSize: 12, fontWeight: 600, color: "#6b7280", letterSpacing: "0.03em" }}>
                  Role
                </th>
                <th style={{ width: 40 }} /> {/* Remove button column */}
              </tr>
            </thead>
            <tbody>
              {/* Empty state — shown when no workers have been assigned */}
              {rows.length === 0 ? (
                <tr>
                  <td colSpan={3} style={{ padding: "24px 28px", color: "#9ca3af", fontSize: 13, textAlign: "center" }}>
                    No team members assigned yet
                  </td>
                </tr>
              ) : rows.map((w) => (
                <tr key={w.id} style={{ borderTop: "1px solid #f3f4f6" }}>
                  <td style={{ padding: "11px 28px", fontSize: 13, color: "#374151" }}>{w.name}</td>
                  <td style={{ padding: "11px 16px", fontSize: 13, color: "#374151" }}>{w.assignedRole}</td>
                  <td style={{ padding: "11px 16px", textAlign: "center" }}>
                    {/* Remove button — calls handleRemove with this worker's ID */}
                    <button
                      onClick={() => handleRemove(w.id)}
                      style={{ background: "none", border: "none", color: "#9ca3af", cursor: "pointer", fontSize: 16, lineHeight: 1, padding: "2px 6px" }}
                    >
                      ×
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* ── Modal Footer — Cancel and Save ── */}
        <div style={{ display: "flex", justifyContent: "flex-end", gap: 10, padding: "16px 28px", borderTop: "1px solid #f3f4f6" }}>

          {/* Cancel — closes modal without saving, discarding all local changes */}
          <button
            onClick={onClose}
            style={{ padding: "9px 20px", background: "#fff", border: "1px solid #d1d5db", borderRadius: 8, fontSize: 13, fontWeight: 500, color: "#374151", cursor: "pointer" }}
          >
            Cancel
          </button>

          {/* Save — passes updated rows back to parent via onSave prop, then closes */}
          <button
            onClick={() => { onSave(rows); onClose() }}
            style={{ padding: "9px 20px", background: "#2563eb", border: "none", borderRadius: 8, fontSize: 13, fontWeight: 600, color: "#fff", cursor: "pointer", display: "flex", alignItems: "center", gap: 6 }}
          >
            Save
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── PROJECT DETAIL VIEW ──────────────────────────────────────────────────────
// Shows the full detail for a selected project including:
//   - Project header with status badge, metadata, and circular progress ring
//   - AI System Insight banner
//   - Tab navigation (Overview / Resources / Timeline)
//   - Task Workflow Progress — progress bars per milestone
//   - Materials Status — colour-coded delivery cards
//   - Workforce Allocation — avatar grid + add button
//
// Props:
//   project    — the selected Project object to display
//   onBack     — called when the user clicks Back to Dashboard
//   allWorkers — full list of available workers (fetched from backend)
function ProjectDetail({
  project,
  onBack,
  allWorkers,
}: {
  project: Project
  onBack: () => void
  allWorkers: Worker[]
}) {
  // Controls whether the AllocationModal is visible
  const [showModal, setShowModal] = useState(false)

  // Local workforce state — initialised from the project prop.
  // Updated when the AllocationModal saves changes.
  const [workforce, setWorkforce] = useState<ProjectWorker[]>(project.workforce)

  // Controls which tab is active in the detail view
  const [activeTab, setActiveTab] = useState<"Overview" | "Resources" | "Timeline">("Overview")

  // Get status badge colours — falls back to Planning style if status is unrecognised
  const statusStyle = STATUS_COLOURS[project.status] ?? STATUS_COLOURS["Planning"]

  return (
    <div style={{ flex: 1, overflow: "auto", background: "#f9fafb" }}>

      {/* ── Back Navigation ── */}
      <div style={{ padding: "16px 32px 0" }}>
        <button
          onClick={onBack} // returns to ProjectsList by setting selectedProject to null
          style={{ display: "flex", alignItems: "center", gap: 6, background: "none", border: "none", color: "#6b7280", fontSize: 13, cursor: "pointer", padding: 0 }}
        >
          ← Back to Dashboard
        </button>
      </div>

      {/* ── Main Card ── */}
      <div style={{ margin: "16px 32px 24px", background: "#fff", borderRadius: 12, border: "1px solid #e5e7eb", boxShadow: "0 1px 4px rgba(0,0,0,0.04)", overflow: "hidden" }}>

        {/* ── Project Header ── */}
        {/* Code badge, status badge, project name, metadata row, circular progress ring */}
        <div style={{ padding: "24px 28px", borderBottom: "1px solid #f3f4f6", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div style={{ flex: 1 }}>

            {/* Project code and status badge */}
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
              <span style={{ fontSize: 12, color: "#9ca3af" }}>{project.code}</span>
              <span style={{ fontSize: 11, fontWeight: 600, background: statusStyle.bg, color: statusStyle.text, padding: "2px 10px", borderRadius: 99 }}>
                {project.status}
              </span>
            </div>

            <h1 style={{ fontSize: 22, fontWeight: 700, color: "#111827", margin: "0 0 14px" }}>
              {project.name}
            </h1>

            {/* Metadata row — department, location, dates */}
            <div style={{ display: "flex", gap: 28, flexWrap: "wrap" }}>
              {[
                { text: project.department },
                { text: project.location },
                { text: `Start: ${project.startDate}` },
                { text: `Delivery: ${project.deliveryDate}` },
              ].map((m) => (
                <span key={m.text} style={{ fontSize: 13, color: "#6b7280" }}>{m.text}</span>
              ))}
            </div>
          </div>

          {/* Circular SVG progress ring — shows overall project completion */}
          <CircleProgress pct={project.progress} />
        </div>

        {/* ── AI Insight Banner ── */}
        {/* Shows the AI-generated insight for this project with confidence score */}
        <div style={{ margin: "20px 28px", background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 10, padding: "14px 18px", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
              {/* Green checkmark icon */}
              <span style={{ width: 16, height: 16, borderRadius: "50%", background: "#16a34a", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 10, flexShrink: 0 }}>✓</span>
              <span style={{ fontWeight: 600, fontSize: 14, color: "#15803d" }}>AI System Insight</span>
            </div>
            <div style={{ fontSize: 14, fontWeight: 600, color: "#166534" }}>{project.aiInsight.message}</div>
            <div style={{ fontSize: 12, color: "#4ade80", marginTop: 3 }}>{project.aiInsight.detail}</div>
          </div>
          {/* Confidence percentage badge */}
          <span style={{ fontSize: 12, color: "#16a34a", fontWeight: 600, background: "#dcfce7", padding: "3px 10px", borderRadius: 99, whiteSpace: "nowrap" }}>
            {project.aiInsight.confidence}% confidence
          </span>
        </div>

        {/* ── Tab Navigation ── */}
        {/* Active tab has a blue bottom border; inactive tabs are grey */}
        {/* Resources and Timeline tabs are placeholders for future sprints */}
        <div style={{ padding: "0 28px", borderBottom: "1px solid #f3f4f6" }}>
          <div style={{ display: "flex", gap: 0 }}>
            {(["Overview", "Resources", "Timeline"] as const).map((tab) => {
              const active = activeTab === tab
              return (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  style={{
                    padding: "10px 20px", background: "none", border: "none",
                    borderBottom: active ? "2px solid #2563eb" : "2px solid transparent",
                    color: active ? "#2563eb" : "#6b7280",
                    fontWeight: active ? 600 : 400,
                    fontSize: 13, cursor: "pointer", marginBottom: -1,
                  }}
                >
                  {tab}
                </button>
              )
            })}
          </div>
        </div>

        {/* ── Tab Body ── */}
        <div style={{ padding: "24px 28px" }}>

          {/* ── Task Workflow Progress ── */}
          {/* Shows each project milestone with a progress bar and completion indicator */}
          {/* Green checkmark circle = complete, empty circle = in progress */}
          <div style={{ marginBottom: 28 }}>
            <div style={{ marginBottom: 16, fontSize: 14, fontWeight: 600, color: "#374151" }}>
              Task Workflow Progress
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {project.tasks.map((task) => {
                const color = progressColor(task.progress)
                return (
                  <div key={task.name}>
                    {/* Task label row — completion icon + name + percentage */}
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 5, fontSize: 13 }}>
                      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        {/* Circle indicator — green with checkmark if 100%, empty grey otherwise */}
                        <span style={{
                          width: 18, height: 18, borderRadius: "50%",
                          background: task.progress === 100 ? "#22c55e" : "#e5e7eb",
                          border: task.progress === 100 ? "none" : "2px solid #d1d5db",
                          display: "inline-flex", alignItems: "center", justifyContent: "center",
                          fontSize: 10, color: "#fff", flexShrink: 0,
                        }}>
                          {task.progress === 100 ? "✓" : ""}
                        </span>
                        <span style={{ color: "#374151" }}>{task.name}</span>
                      </div>
                      <span style={{ color: "#6b7280", fontSize: 12 }}>{task.progress}%</span>
                    </div>
                    {/* Progress bar — width set as percentage, colour from progressColor() */}
                    <div style={{ height: 6, background: "#f3f4f6", borderRadius: 99, overflow: "hidden" }}>
                      <div style={{
                        height: "100%", width: `${task.progress}%`,
                        background: color, borderRadius: 99,
                        transition: "width 0.4s ease", // smooth animation on load
                      }} />
                    </div>
                  </div>
                )
              })}
            </div>
          </div>

          {/* ── Materials Status ── */}
          {/* Shows each required material as a card with colour-coded delivery status */}
          {/* Delivered = green, In Transit = amber, Pending = grey */}
          <div style={{ marginBottom: 28 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: "#374151" }}>Materials Status</div>
              {/* + Add button — placeholder for future material addition functionality */}
              <button style={{ padding: "5px 14px", border: "1px solid #d1d5db", borderRadius: 7, background: "#fff", fontSize: 12, color: "#374151", cursor: "pointer" }}>
                + Add
              </button>
            </div>

            <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
              {project.materials.map((mat) => {
                // Determine badge colour based on material delivery status
                const statColor = mat.status === "Delivered"
                  ? { text: "#16a34a", bg: "#dcfce7" } // green
                  : mat.status === "In Transit"
                  ? { text: "#d97706", bg: "#fef3c7" } // amber
                  : { text: "#6b7280", bg: "#f3f4f6" } // grey — Pending
                return (
                  <div key={mat.name} style={{ flex: "1 1 180px", border: "1px solid #f3f4f6", borderRadius: 10, padding: "14px 16px", background: "#fafafa" }}>
                    {/* Status badge */}
                    <div style={{ fontSize: 11, fontWeight: 600, color: statColor.text, background: statColor.bg, display: "inline-block", padding: "2px 9px", borderRadius: 99, marginBottom: 8 }}>
                      {mat.status}
                    </div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: "#111827" }}>{mat.name}</div>
                    <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 2 }}>{mat.qty}</div>
                  </div>
                )
              })}
            </div>
          </div>

          {/* ── Workforce Allocation ── */}
          {/* Shows assigned team members as avatar cards with name, role, and status */}
          {/* The + Add button opens the AllocationModal */}
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: "#374151" }}>Workforce Allocation</div>
              {/* Opens AllocationModal — setShowModal(true) triggers conditional render below */}
              <button
                onClick={() => setShowModal(true)}
                style={{ padding: "5px 14px", border: "1px solid #d1d5db", borderRadius: 7, background: "#fff", fontSize: 12, color: "#374151", cursor: "pointer" }}
              >
                + Add
              </button>
            </div>

            {/* Empty state message if no workers assigned yet */}
            {workforce.length === 0 ? (
              <div style={{ fontSize: 13, color: "#9ca3af", padding: "8px 0" }}>
                No team members assigned. Click add to assign workers.
              </div>
            ) : (
              // Avatar grid — each worker shown as a coloured circle with initials
              <div style={{ display: "flex", gap: 20, flexWrap: "wrap" }}>
                {workforce.map((w) => {
                  // avatarColor() generates a consistent colour from the worker's name
                  const color = avatarColor(w.name)
                  return (
                    <div key={w.id} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 6 }}>
                      {/* Avatar circle — shows first two initials of full name */}
                      <div style={{ width: 44, height: 44, borderRadius: "50%", background: color, color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, fontWeight: 700 }}>
                        {w.name.split(" ").map((p) => p[0]).join("").slice(0, 2)}
                      </div>
                      {/* Name, assigned role, and status label below the avatar */}
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 12, fontWeight: 600, color: "#374151" }}>{w.name}</div>
                        <div style={{ fontSize: 11, color: "#9ca3af" }}>{w.assignedRole}</div>
                        {/* Status label — green for completed, blue for active */}
                        {w.status && (
                          <div style={{ fontSize: 10, color: w.status === "completed" ? "#16a34a" : "#2563eb", marginTop: 2 }}>
                            {w.status}
                          </div>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── Allocation Modal ── */}
      {/* Conditionally rendered — only mounts when showModal is true */}
      {showModal && (
        <AllocationModal
          workers={workforce}
          onClose={() => setShowModal(false)}
          onSave={(updated) => {
            setWorkforce(updated) // update local workforce state with saved changes
            toast.success("Workforce updated successfully") // Sonner toast notification
          }}
        />
      )}
    </div>
  )
}

// ─── PROJECTS LIST VIEW ───────────────────────────────────────────────────────
// Renders all projects as clickable cards in a vertical list.
// Each card shows: project code, status badge, name, department, location,
// progress percentage, and a chevron indicating it's clickable.
//
// Hover effect is applied using onMouseEnter/Leave rather than CSS classes
// because this component uses inline styles throughout.
//
// Props:
//   onSelect — callback fired with the clicked Project object,
//              which sets selectedProject in the parent to trigger the detail view
function ProjectsList({ onSelect }: { onSelect: (p: Project) => void }) {
  return (
    <div style={{ flex: 1, padding: "28px 32px", overflow: "auto", background: "#f9fafb" }}>
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", margin: 0 }}>Projects</h2>
        <p style={{ fontSize: 13, color: "#6b7280", marginTop: 4 }}>
          {MOCK_PROJECTS.length} projects total
        </p>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        {MOCK_PROJECTS.map((project) => {
          const statusStyle = STATUS_COLOURS[project.status] ?? STATUS_COLOURS["Planning"]
          return (
            <div
              key={project.id}
              onClick={() => onSelect(project)} // passes project to parent, triggers detail view
              style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 12, padding: "20px 24px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "box-shadow 0.15s" }}
              // Hover shadow applied inline since we're using inline styles not Tailwind
              onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.boxShadow = "0 4px 16px rgba(0,0,0,0.08)" }}
              onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.boxShadow = "none" }}
            >
              <div>
                {/* Code + status badge row */}
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
                  <span style={{ fontSize: 12, color: "#9ca3af" }}>{project.code}</span>
                  <span style={{ fontSize: 11, fontWeight: 600, background: statusStyle.bg, color: statusStyle.text, padding: "2px 10px", borderRadius: 99 }}>
                    {project.status}
                  </span>
                </div>
                <div style={{ fontSize: 16, fontWeight: 600, color: "#111827" }}>{project.name}</div>
                <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 4 }}>
                  {project.department} · {project.location}
                </div>
              </div>

              {/* Right side — progress percentage + chevron */}
              <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
                <div style={{ textAlign: "right" }}>
                  {/* Colour of the percentage matches the progress level */}
                  <div style={{ fontSize: 22, fontWeight: 700, color: progressColor(project.progress) }}>
                    {project.progress}%
                  </div>
                  <div style={{ fontSize: 11, color: "#9ca3af" }}>Progress</div>
                </div>
                {/* Chevron hints this row is clickable */}
                <span style={{ color: "#d1d5db", fontSize: 18 }}>›</span>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ─── MAIN PAGE COMPONENT ──────────────────────────────────────────────────────
// Root component for the /workforce route.
// Responsible for:
//   1. Fetching the available worker list from the backend on mount
//   2. Managing which nav item is active in the sidebar
//   3. Managing selectedProject state — null = list view, set = detail view
//   4. Rendering the topbar, sidebar, and the appropriate content view
function WorkforcePage() {
  // Available employees — populated from backend on mount
  const [workers, setWorkers] = useState<Worker[]>([])

  // Tracks which sidebar nav item is active — defaults to Projects
  const [activeNav, setActiveNav] = useState("Projects")

  // Master-detail state — null shows ProjectsList, a project object shows ProjectDetail
  // This is the core navigation mechanism for this page — no router involved
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)

  // Fetch available workers from the backend on component mount.
  // Empty dependency array [] means this runs once when the page first loads.
  // If the API call fails (catch block), falls back to a hardcoded mock list
  // so the AllocationModal still has employees to show.
  useEffect(() => {
    getWorkforce()
      .then(setWorkers) // on success: update workers state with API response
      .catch(() =>
        // on failure: use fallback mock data so the page remains functional
        setWorkers([
          { id: 1, name: "Alice Martin", role: "Frontend Developer" },
          { id: 2, name: "Bob Chen",     role: "Backend Developer"  },
          { id: 3, name: "Charlie Davis",role: "Security Engineer"  },
        ]),
      )
  }, [])

  return (
    <div style={{
      display: "flex", flexDirection: "column",
      height: "100vh",
      fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
      background: "#f9fafb",
      color: "#111827",
    }}>

      {/* ── TOPBAR ── */}
      {/* Fixed height header containing GAMA logo, page title, and user info */}
      <header style={{
        display: "flex", justifyContent: "space-between", alignItems: "center",
        padding: "0 24px", height: 56,
        background: "#fff", borderBottom: "1px solid #e5e7eb",
        boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
        flexShrink: 0, // prevents header shrinking in flex layout
        zIndex: 10,    // stays above scrollable content
      }}>

        {/* Brand — GAMA logo + divider + company name and subtitle */}
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <img src="/assets/images/gama-logo.png" alt="GAMA Consulting" style={{ height: 38, objectFit: "contain" }} />
          <div style={{ width: 1, height: 28, background: "#e5e7eb" }} />
          <div>
            <div style={{ fontSize: 13, fontWeight: 700, color: "#111827", lineHeight: 1.2 }}>GAMA Consulting</div>
            <div style={{ fontSize: 10, color: "#9ca3af" }}>Project Management System</div>
          </div>
        </div>

        {/* Page title centred in the header */}
        <div style={{ fontSize: 14, fontWeight: 600, color: "#374151", letterSpacing: "0.01em" }}>
          AI Project Management Platform
        </div>

        {/* User info — name, role, avatar initials, logout button */}
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: "#111827" }}>Harri Rassias</div>
            <div style={{ fontSize: 11, color: "#9ca3af" }}>Structural Engineer</div>
          </div>
          {/* Avatar circle with initials — HR for Harri Rassias */}
          <div style={{ width: 34, height: 34, borderRadius: "50%", background: "#2563eb", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 700, color: "#fff" }}>
            HR
          </div>
          <button style={{ display: "flex", alignItems: "center", gap: 5, padding: "6px 14px", border: "1px solid #e5e7eb", borderRadius: 7, background: "#fff", fontSize: 12, color: "#6b7280", cursor: "pointer" }}>
            Logout
          </button>
        </div>
      </header>

      {/* ── BODY — sidebar + content ── */}
      <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>

        {/* ── SIDEBAR ── */}
        {/* Vertical nav — highlights the active item in blue */}
        {/* Clicking a non-Projects item clears selectedProject to avoid showing stale detail */}
        <nav style={{ width: 220, background: "#fff", borderRight: "1px solid #e5e7eb", padding: "20px 12px", display: "flex", flexDirection: "column", gap: 2, flexShrink: 0 }}>
          {NAV_ITEMS.map((item) => {
            const active = activeNav === item.label
            return (
              <button
                key={item.label}
                onClick={() => {
                  setActiveNav(item.label)
                  // Reset detail view if navigating away from Projects
                  if (item.label !== "Projects") setSelectedProject(null)
                }}
                style={{
                  display: "flex", alignItems: "center", gap: 10,
                  width: "100%", padding: "9px 14px", borderRadius: 8, border: "none",
                  background: active ? "#eff6ff" : "transparent",
                  color: active ? "#2563eb" : "#6b7280",
                  fontSize: 13, fontWeight: active ? 600 : 400,
                  cursor: "pointer", textAlign: "left",
                  transition: "all 0.12s",
                }}
                onMouseEnter={(e) => { if (!active) (e.currentTarget as HTMLElement).style.background = "#f9fafb" }}
                onMouseLeave={(e) => { if (!active) (e.currentTarget as HTMLElement).style.background = "transparent" }}
              >
                {item.label}
              </button>
            )
          })}
        </nav>

        {/* ── MAIN CONTENT AREA ── */}
        {/* Conditionally renders based on activeNav and selectedProject state:
            - activeNav === "Projects" AND selectedProject set → ProjectDetail
            - activeNav === "Projects" AND selectedProject null → ProjectsList
            - activeNav !== "Projects" → "coming soon" placeholder */}
        {activeNav === "Projects" ? (
          selectedProject ? (
            <ProjectDetail
              project={selectedProject}
              onBack={() => setSelectedProject(null)} // clears selection, returns to list
              allWorkers={workers}
            />
          ) : (
            <ProjectsList onSelect={setSelectedProject} />
          )
        ) : (
          // Placeholder for nav items not yet implemented
          <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", color: "#9ca3af", fontSize: 14 }}>
            {activeNav} — coming soon
          </div>
        )}
      </div>
    </div>
  )
}
